<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);CA1724;CA1303</NoWarn>
  </PropertyGroup>

  <PropertyGroup Label="NuGet">
    <PackAsTool>true</PackAsTool>
    <ToolCommandName>tcd</ToolCommandName>
    <Description>Automates local actions providing set of tools for LLMs</Description>
    <PackageTags>cli;automation;local;actions;tools;llms;llm;ai</PackageTags>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.CommandLine" Version="2.0.10" />
  </ItemGroup>

</Project>
